### PR TITLE
Add DeleteAfter parameter to Quota

### PR DESCRIPTION
**Pull request by machacekondra**
This patch add a DeleteAfter parameter, which define number of hours the template instance should be alive. If the time expires the template instance will be automatically removed.

### CODE REVIEW

**Comment by machacekondra** [comment]
@rawagner PTAL

**Comment by machacekondra** [comment]
Should the paramater be in hours or minutes? WDYT?

**Comment by rawagner** [comment]
looks great. Can we use the same parsing logic for time as Hive ? https://github.com/openshift/hive/blob/master/apis/hive/v1/clusterclaim_types.go#L24-L34

**Comment by machacekondra** [comment]
> looks great. Can we use the same parsing logic for time as Hive ? https://github.com/openshift/hive/blob/master/apis/hive/v1/clusterclaim_types.go#L24-L34

Oh sure, this method looks cool.

**Comment by rawagner** [comment]
/lgtm

can you rebase ?

**Pull request merged**
