### PR TITLE
Allow to run day2 only

### PR DESCRIPTION
**Pull request by machacekondra**
Demo example: https://asciinema.org/a/580457

### CODE REVIEW

**Review by rawagner — CHANGES_REQUESTED** [review]

**Comment by machacekondra** [comment]
Comments fixed.

**Comment by machacekondra** [comment]
The test fails because of race condition in tests, it's fixed here: https://github.com/stolostron/cluster-templates-operator/pull/121/files#diff-72dc2ce54223c3c017525e285df9d5a5115813da973fd5a4b3502a2b12dec6c5R61

**Comment by machacekondra** [comment]
Rebased

**Pull request merged**
