### PR TITLE
Add nodeport address value

### PR DESCRIPTION
**Pull request by machacekondra**
Signed-off-by: Ondra Machacek <omachace@redhat.com>

### CODE REVIEW

**Comment by machacekondra** [comment]
@rawagner Does it makes sense to have it for kubevirt as well?

**Comment by rawagner** [comment]
Yes, i think so!

**Comment by machacekondra** [comment]
> Yes, i think so!

Done

**Review by rawagner — CHANGES_REQUESTED** [review]
the `hypershift-kubevirt-template` version is not updated in `index.yaml`

We should also include the new `values` in the helm chart schemas

**Pull request merged**
